export {default as Kid1} from './Kid1.png'
export {default as Kid2} from './Kid2.png'
export {default as Kid3} from './Kid3.png'
export {default as Kid4} from './Kid4.png'
export {default as Kid5} from './Kid5.png'
export {default as Kid6} from './Kid6.png'